### ISSUE TITLE
Menu items inreadable in GTK 3.10 and newer

### ISSUE THREAD

**Issue by dmdobrowolski** [rbrito/pkg-mediterranean-gtk-themes#4]
In apps using GTK 3.10 an newer menu items are almost inreadable because of the background filled with white.

PS Adding a file gtk.css to ~/.config/gtk-3.0/ with a code

``` css
.menuitem * { background-color: transparent }
```

solved a problem for me.
